name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build and run tests
        run: ./mvnw clean test

  codeql:
    name: CodeQL SAST Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Build project
        run: ./mvnw clean compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
  
  dependency-scan:
    name: Dependency Vulnerability Scan (SCA)
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
  docker-build:
    name: Docker Image Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build application JAR
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t log-analyzer:ci .
  image-scan:
    name: Container Image Security Scan
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build application JAR
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t log-analyzer:scan .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: log-analyzer:scan
          severity: HIGH

  runtime-test:
    name: Container Runtime Smoke Test
    runs-on: ubuntu-latest
    needs: image-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build application JAR
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t log-analyzer:runtime .

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name log-analyzer-test log-analyzer:runtime
          sleep 10

      - name: Smoke test endpoint
        run: |
          curl -f http://localhost:8080/ping

      - name: Stop container
        run: docker stop log-analyzer-test

  docker-push:
    name: Push Trusted Image to DockerHub
    runs-on: ubuntu-latest
    needs: runtime-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build application JAR
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/log-analyzer:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/log-analyzer:latest


